'use strict';

const state = { books: [], user: null, currentBook: null, pages: [], page: 0, bookmarks: {}, theme: localStorage.getItem('budka-theme') || 'classic' };
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const api = async (path, options = {}) => { const r = await fetch(path, { credentials:'same-origin', headers:{'Content-Type':'application/json', ...(options.headers||{})}, ...options }); const data = await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error || `HTTP ${r.status}`); return data; };
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',(id==='catalog'&&b.id==='catalogNav')||(id==='admin'&&b.id==='adminNav')));location.hash=id==='catalog'?'catalog':id}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bookCategory(b){const x=(`${b.title} ${b.author||''} ${b.description||''}`).toLowerCase();if(/сталькер|зов припяти|лукьяненко|фантаст/.test(x))return 'fantasy';if(/скайрим|толкин|перумов|ранобэ|фэнтези|ветер в твоих волосах/.test(x))return 'fantasy2';if(/каренин|город грехов|приключ/.test(x))return 'adventure';return 'other'}
function bookCover(b,cls='book-cover'){const text=esc((b.title||'Книга').slice(0,22));return `<div class="${cls}"><span>${text}</span></div>`}
function renderBooks(){const grid=$('#bookGrid'),list=$('#libraryList');const query=(state.search||'').trim().toLowerCase();const cat=state.category||'all';let books=state.books.filter(b=>(!query||`${b.title} ${b.author||''} ${b.description||''}`.toLowerCase().includes(query))&&(cat==='all'||bookCategory(b)===cat));$('#bookCount').textContent=state.books.length;if(!books.length){grid.innerHTML='<div class="empty"><i class="fa-solid fa-book-open"></i><p>По этому запросу книг не найдено.</p></div>'}else{grid.innerHTML=books.map(b=>`<article class="book-card"><div>${bookCover(b)}</div><div><h2>${esc(b.title)}</h2><div class="author">${esc(b.author||'Неизвестный автор')}</div><p>${esc(b.description||'Без описания')}</p></div><div class="book-meta"><span class="hint">${bookCategory(b)==='fantasy'?'Фантастика':bookCategory(b)==='fantasy2'?'Фэнтези':bookCategory(b)==='adventure'?'Приключения':'Другое'}</span><div class="book-actions"><button class="btn primary" data-read="${b.id}"><i class="fa-solid fa-book-open"></i><span> Читать</span></button>${state.user?.role==='admin'?`<button class="btn" title="Редактировать" data-edit="${b.id}"><i class="fa-solid fa-pen"></i></button><button class="btn danger" title="Удалить" data-delete="${b.id}"><i class="fa-solid fa-trash"></i></button>`:''}</div></div></article>`).join('')}
if(list){list.innerHTML=state.books.map(b=>`<button class="library-item ${state.currentBook?.id===b.id?'active':''}" data-read="${b.id}">${bookCover(b,'cover-thumb')}<span class="library-meta"><strong>${esc(b.title)}</strong><small>${esc(b.author||'Неизвестный автор')}</small></span></button>`).join('')}}
async function loadBooks(){state.books=await api('/api/books');renderBooks()}
function paginate(text){const chunks=text.split(/\n\s*\n/).filter(Boolean);const pages=[];let cur='';const limit=1200;for(const chunk of chunks){const add=(cur?'\n\n':'')+chunk;if((cur+add).length>limit){if(cur)pages.push(cur);if(chunk.length<=limit)cur=chunk;else{for(let i=0;i<chunk.length;i+=limit)pages.push(chunk.slice(i,i+limit));cur=''}}else cur+=add}if(cur)pages.push(cur);return pages.length?pages:[''];}
function openReader(book){state.currentBook=book;state.pages=paginate(book.content);const saved=Number(localStorage.getItem('bookmark:'+book.id)||0);state.page=Math.min(saved,state.pages.length-1);$('#readerBookTitle').textContent=book.title;$('#readerCover').innerHTML=esc((book.title||'К').slice(0,8));const slider=$('#pageSlider');if(slider){slider.max=Math.max(0,state.pages.length-1);slider.value=state.page}showView('reader');renderPage()}
function renderPage(direction){const a=$('#pageA'),b=$('#pageB');a.classList.remove('flip-next','flip-prev');b.classList.remove('flip-next','flip-prev');void a.offsetWidth;if(direction)a.classList.add(direction==='next'?'flip-next':'flip-prev');const mobile=matchMedia('(max-width:800px)').matches;a.textContent=state.pages[state.page]||'';b.textContent=mobile?'':(state.pages[state.page+1]||'');const total=mobile?state.pages.length:Math.ceil(state.pages.length/2);const shown=mobile?state.page:Math.floor(state.page/2);$('#pageLabel').textContent=`${Math.min(shown+1,total)} / ${total}`;$('#progressBar').style.width=`${((shown+1)/total)*100}%`;const bm=Number(localStorage.getItem('bookmark:'+state.currentBook.id)||-1);$('#bookmarkState').innerHTML=bm===shown?'<i class="fa-solid fa-bookmark"></i> Закладка установлена':'<i class="fa-regular fa-bookmark"></i> Закладка не установлена';if($('#pageSlider'))$('#pageSlider').value=state.page;$('#bookmarkBtn').innerHTML=bm===shown?'<i class="fa-solid fa-bookmark"></i><span>Закладка</span>':'<i class="fa-regular fa-bookmark"></i><span>Закладка</span>'}
function step(delta){const mobile=matchMedia('(max-width:800px)').matches;const inc=mobile?delta:delta*2;const next=Math.max(0,Math.min(state.pages.length-1,state.page+inc));if(next===state.page)return;state.page=next;renderPage(delta>0?'next':'prev');playFlip()}
let audioCtx;function beep(freq,duration,type='sine'){try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.05,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration+.02)}catch(_){}}
function playFlip(){beep(160,.06,'triangle');setTimeout(()=>beep(90,.08,'triangle'),25)}
function playDice(){beep(110,.08,'square');setTimeout(()=>beep(180,.08,'square'),70);setTimeout(()=>beep(250,.06,'square'),140)}
const themes=['classic','stalker','skyrim','anime','comic','night'];function setTheme(t){state.theme=t;localStorage.setItem('budka-theme',t);document.body.dataset.theme=t;$('#geiger').hidden=t!=='stalker';if(t==='stalker')startRadio();if(t==='anime')startPetals();else stopPetals();$$('.theme-choice').forEach(b=>b.classList.toggle('active',b.dataset.setTheme===t));toast(`Тема: ${t}`)}
function cycleTheme(){setTheme(themes[(themes.indexOf(state.theme)+1)%themes.length])}
let radioTimer;function startRadio(){clearInterval(radioTimer);const lines=['«Приём. Будка на связи.»','«Не трогай артефакт без перчаток.»','«Шорох слева. Это книга.»','«Читатель, ты ещё здесь?»'];let i=0;$('#radioLine').textContent=lines[0];radioTimer=setInterval(()=>{$('#radioLine').textContent=lines[i++%lines.length]},4000)}
let petalsTimer;function startPetals(){stopPetals();const c=$('#petals'),x=c.getContext('2d');let ps=[];function resize(){c.width=innerWidth;c.height=innerHeight}resize();addEventListener('resize',resize);for(let i=0;i<45;i++)ps.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,s:4+Math.random()*7,v:.4+Math.random()*1.2,r:Math.random()*6});function frame(){if(document.body.dataset.theme!=='anime')return;x.clearRect(0,0,c.width,c.height);for(const p of ps){p.y+=p.v;p.x+=Math.sin(p.y/40)*.5;p.r+=.02;if(p.y>c.height+20){p.y=-20;p.x=Math.random()*c.width}x.save();x.translate(p.x,p.y);x.rotate(p.r);x.beginPath();x.moveTo(0,0);x.bezierCurveTo(p.s,-p.s,p.s,p.s,0,p.s*1.5);x.bezierCurveTo(-p.s,p.s,-p.s,-p.s,0,0);x.fillStyle='rgba(255,145,199,.55)';x.fill();x.restore()}petalsTimer=requestAnimationFrame(frame)}frame()}
function stopPetals(){if(petalsTimer)cancelAnimationFrame(petalsTimer);const c=$('#petals');c.getContext('2d')?.clearRect(0,0,c.width,c.height)}
function openModal(id){$('#'+id).hidden=false}function closeModal(id){$('#'+id).hidden=true}
function updateProfileChip(){const n=$('.profile-name');if(n)n.textContent=state.user?.username||'Гость'}
function renderProfile(){const c=$('#profileContent');if(!state.user)c.innerHTML='<p>Вы гость. Войдите или зарегистрируйтесь.</p><button class="btn primary" id="openLogin"><i class="fa-solid fa-right-to-bracket"></i> Войти</button>';else c.innerHTML=`<p><strong>${esc(state.user.username)}</strong></p><p>Роль: <span class="badge">${state.user.role}</span></p><div class="form-actions">${state.user.role==='admin'?'<button class="btn" id="adminBtn"><i class="fa-solid fa-users-gear"></i> Администрирование</button>':''}<button class="btn" id="changePasswordBtn"><i class="fa-solid fa-key"></i> Сменить пароль</button><button class="btn danger" id="logoutBtn"><i class="fa-solid fa-right-from-bracket"></i> Выйти</button></div>`}
async function refreshMe(){state.user=(await api('/api/me')).user;document.body.classList.toggle('is-admin',state.user?.role==='admin');updateProfileChip();renderBooks()}
async function login(form){const fd=new FormData(form);try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(fd))});state.user=d.user;document.body.classList.toggle('is-admin',d.user.role==='admin');closeModal('loginModal');closeModal('profileModal');updateProfileChip();renderBooks();toast('Вход выполнен')}catch(e){$('#loginError').textContent=e.message}}
async function register(form){const fd=new FormData(form);try{await api('/api/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(fd))});toast('Читатель зарегистрирован');form.reset()}catch(e){toast(e.message)}}
async function changePassword(){if(!state.user)return;const currentPassword=prompt('Текущий пароль:');if(currentPassword===null)return;const newPassword=prompt('Новый пароль (минимум 8 символов):');if(newPassword===null)return;const repeatPassword=prompt('Повторите новый пароль:');if(repeatPassword===null)return;if(newPassword!==repeatPassword){toast('Пароли не совпадают');return}try{await api('/api/auth/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});toast('Пароль изменён')}catch(e){toast(e.message)}}
function editBook(book){const f=$('#bookForm');$('#bookFormTitle').innerHTML='<i class="fa-solid fa-pen-to-square"></i> Редактирование';f.id.value=book.id;f.title.value=book.title;f.author.value=book.author||'';f.description.value=book.description||'';f.content.value=book.content;openModal('bookModal')}
async function saveBook(form){const data=Object.fromEntries(new FormData(form));try{await api(data.id?`/api/books/${data.id}`:'/api/books',{method:data.id?'PUT':'POST',body:JSON.stringify(data)});closeModal('bookModal');await loadBooks();toast('Книга сохранена')}catch(e){toast(e.message)}}
async function deleteBook(id){if(!confirm('Удалить книгу без возможности восстановления?'))return;try{await api('/api/books/'+id,{method:'DELETE'});await loadBooks();toast('Книга удалена')}catch(e){toast(e.message)}}
async function loadUsers(){const users=await api('/api/users');$('#userTable').innerHTML=users.map(u=>`<div class="user-row"><div><strong>${esc(u.username)}</strong><div class="hint">${new Date(u.createdAt).toLocaleString('ru-RU')}</div></div><select class="role-select" data-user="${u.id}"><option value="reader" ${u.role==='reader'?'selected':''}>reader</option><option value="admin" ${u.role==='admin'?'selected':''}>admin</option></select><button class="btn danger" data-user-delete="${u.id}" title="Удалить"><i class="fa-solid fa-trash"></i></button></div>`).join('')}
async function openAdmin(){if(state.user?.role!=='admin')return;showView('admin');await loadUsers()}
async function changeRole(id,role){try{await api('/api/users/'+id,{method:'PUT',body:JSON.stringify({role})});toast('Роль обновлена');await loadUsers()}catch(e){toast(e.message);await loadUsers()}}
async function deleteUser(id){if(!confirm('Удалить пользователя?'))return;try{await api('/api/users/'+id,{method:'DELETE'});await loadUsers();toast('Пользователь удалён')}catch(e){toast(e.message)}}
const answers=['Бесспорно.','Спроси после следующей страницы.','Да, но только если чай уже налит.','Сейчас лучше не знать.','Вероятность высока.','Поняша одобряет.','Никаких гарантий.','Знаки говорят: да.','Перечитай вопрос.','Сегодня — точно нет.'];
function askBall(){const ball=$('#magicBall');ball.classList.remove('shake');void ball.offsetWidth;ball.classList.add('shake');beep(240,.12,'sine');setTimeout(()=>{$('#magicAnswer').textContent=answers[Math.floor(Math.random()*answers.length)];},280)}
function roll(type){const d1=$('#die1'),d2=$('#die2');d1.classList.remove('roll');d2.classList.remove('roll');void d1.offsetWidth;d1.classList.add('roll');d2.classList.add('roll');const a=1+Math.floor(Math.random()*(type==='2d6'?6:20)),b=type==='2d6'?1+Math.floor(Math.random()*6):0;d1.textContent=a;d2.textContent=type==='2d6'?b:'—';$('#diceResult').textContent=type==='2d6'?`Сумма: ${a+b}`:`Результат: ${a}`;playDice()}

document.addEventListener('click',async e=>{const t=e.target.closest('button,[data-close],[data-read],[data-edit],[data-delete],[data-user-delete]');if(!t)return;if(t.dataset.close)closeModal(t.dataset.close);if(t.dataset.read){const b=state.books.find(x=>x.id===t.dataset.read);if(b)openReader(b)}if(t.dataset.edit){const b=state.books.find(x=>x.id===t.dataset.edit);if(b)editBook(b)}if(t.dataset.delete)deleteBook(t.dataset.delete);if(t.dataset.userDelete)deleteUser(t.dataset.userDelete);if(t.id==='profileBtn'){renderProfile();openModal('profileModal')}if(t.id==='openLogin'){closeModal('profileModal');openModal('loginModal')}if(t.id==='logoutBtn'){await api('/api/auth/logout',{method:'POST'});state.user=null;document.body.classList.remove('is-admin');updateProfileChip();renderBooks();closeModal('profileModal');toast('Вы вышли')}if(t.id==='adminBtn'){closeModal('profileModal');openAdmin()}if(t.id==='changePasswordBtn'){changePassword()}if(t.id==='themeBtn'||t.id==='mobileThemeBtn'){cycleTheme()}if(t.dataset.setTheme){setTheme(t.dataset.setTheme)}if(t.id==='catalogNav'||t.id==='mobileCatalogBtn'){showView('catalog')}if(t.id==='adminNav'){openAdmin()}if(t.id==='mobileAperitifBtn'){openModal('aperitifModal')}if(t.id==='writeBtnSide'){const f=$('#bookForm');f.reset();f.id.value='';$('#bookFormTitle').innerHTML='<i class="fa-solid fa-pen-to-square"></i> Новая книга';openModal('bookModal')}if(t.id==='bookmarkBottomBtn')$('#bookmarkBtn').click();if(t.id==='readerSoundBtn')playFlip();if(t.id==='fullscreenBtn'){const el=$('#reader');if(document.fullscreenElement)document.exitFullscreen?.();else el.requestFullscreen?.()}if(t.id==='closeAperitifSide'){}if(t.id==='aperitifBtn')openModal('aperitifModal');if(t.id==='askBall')askBall();if(t.id==='roll2d6')roll('2d6');if(t.id==='rollD20')roll('d20');if(t.id==='backBtn')showView('catalog');if(t.id==='prevBtn')step(-1);if(t.id==='nextBtn')step(1);if(t.id==='bookmarkBtn'&&state.currentBook){const mobile=matchMedia('(max-width:800px)').matches;const p=mobile?state.page:Math.floor(state.page/2);const key='bookmark:'+state.currentBook.id;const old=Number(localStorage.getItem(key)||-1);if(old===p)localStorage.removeItem(key);else localStorage.setItem(key,p);renderPage() }if(t.id==='writeBtn'){const f=$('#bookForm');f.reset();f.id.value='';$('#bookFormTitle').innerHTML='<i class="fa-solid fa-pen-to-square"></i> Новая книга';openModal('bookModal')}});
document.addEventListener('change',e=>{if(e.target.matches('.role-select'))changeRole(e.target.dataset.user,e.target.value)});
$('#searchBooks').addEventListener('input',e=>{state.search=e.target.value;const m=$('#mobileSearchInput');if(m)m.value=e.target.value;renderBooks()});$('#mobileSearchInput').addEventListener('input',e=>{state.search=e.target.value;$('#searchBooks').value=e.target.value;renderBooks()});$('#closeMobileSearch').addEventListener('click',()=>$('#mobileSearchBar').classList.remove('open'));$('#categoryList').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=b.dataset.category;$$('.category').forEach(x=>x.classList.toggle('active',x===b));renderBooks()});$('#pageSlider').addEventListener('input',e=>{state.page=Number(e.target.value);renderPage()});$('#mobileProfileBtn').addEventListener('click',()=>$('#profileBtn').click());$('#mobileSearchBtn').addEventListener('click',()=>{const bar=$('#mobileSearchBar');bar.classList.toggle('open');if(bar.classList.contains('open'))$('#mobileSearchInput').focus()});document.querySelectorAll('.theme-choice').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.setTheme)));
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login(e.currentTarget)});$('#registerForm').addEventListener('submit',e=>{e.preventDefault();register(e.currentTarget)});$('#bookForm').addEventListener('submit',e=>{e.preventDefault();saveBook(e.currentTarget)});addEventListener('keydown',e=>{if($('#reader').classList.contains('active')){if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1)}});addEventListener('resize',()=>{if(state.currentBook&&$('#reader').classList.contains('active'))renderPage()});
(async function init(){document.body.dataset.theme=state.theme;setTheme(state.theme);updateProfileChip();try{await refreshMe();await loadBooks()}catch(e){toast('Не удалось загрузить API: '+e.message)}})();
