'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={books:[],user:null,current:null,pages:[],page:0,theme:localStorage.getItem('budka-theme')||'anime',filter:'all',query:''};
const api=async(path,options={})=>{const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function setTheme(t){state.theme=t;localStorage.setItem('budka-theme',t);document.body.dataset.theme=t;$$('[data-theme-choice]').forEach(b=>b.classList.toggle('selected',b.dataset.themeChoice===t));}
function pagesFromText(text){const blocks=String(text||'').split(/\n\s*\n/).filter(Boolean),out=[];let cur='',limit=1250;for(const block of blocks){const add=(cur?'\n\n':'')+block;if((cur+add).length<=limit)cur+=add;else{if(cur)out.push(cur);if(block.length<=limit)cur=block;else for(let i=0;i<block.length;i+=limit)out.push(block.slice(i,i+limit));cur='';}}if(cur)out.push(cur);return out.length?out:[''];}
function coverText(book){return esc((book.title||'Б').trim().slice(0,1).toUpperCase())}
function filteredBooks(){return state.books.filter(b=>{const q=state.query.toLowerCase();return (!q||`${b.title} ${b.author} ${b.description}`.toLowerCase().includes(q))})}
function renderBooks(){const list=$('#bookList'),books=filteredBooks();$('#bookCount').textContent=state.books.length;list.innerHTML=books.length?books.map(b=>`<button class="book-item ${state.current?.id===b.id?'selected':''}" data-book="${b.id}"><span class="cover">${coverText(b)}</span><span class="book-info"><b>${esc(b.title)}</b><span>${esc(b.author||'Неизвестный автор')}</span></span></button>`).join(''):'<div class="hint" style="padding:20px">Книги не найдены.</div>';}
function renderReader(){if(!state.current)return;const mobile=matchMedia('(max-width:800px)').matches;const total=state.pages.length;const shown=Math.min(state.page,total-1);$('#readerTitle').textContent=state.current.title;$('#readerAuthor').textContent=state.current.author||'Неизвестный автор';$('#readerCover').textContent=coverText(state.current);$('#pageA').textContent=state.pages[shown]||'';$('#pageB').textContent=mobile?'':(state.pages[shown+1]||'');const spreadTotal=mobile?total:Math.max(1,Math.ceil(total/2));const spreadIndex=mobile?shown:Math.floor(shown/2);$('#pageLabel').textContent=spreadIndex+1;$('#pageTotal').textContent=spreadTotal;$('#progressBar').style.width=`${((spreadIndex+1)/spreadTotal)*100}%`;$('#pageSlider').max=Math.max(0,spreadTotal-1);$('#pageSlider').value=spreadIndex;const key=`bookmark:${state.current.id}`;const bm=Number(localStorage.getItem(key)||-1);$('#bookmarkText').textContent=bm>=0?`Закладка: страница ${bm+1}`:'У вас пока нет закладок';}
function openBook(book){state.current=book;state.pages=pagesFromText(book.content);const bm=Number(localStorage.getItem(`bookmark:${book.id}`)||0);state.page=Math.min(bm,state.pages.length-1);renderBooks();renderReader();}
function step(delta){if(!state.current)return;const mobile=matchMedia('(max-width:800px)').matches;const inc=mobile?delta:delta*2;const next=Math.max(0,Math.min(state.pages.length-1,state.page+inc));if(next===state.page)return;state.page=next;renderReader();}
function showSearch(){if(matchMedia('(max-width:800px)').matches){$('#searchInput').focus();$('#libraryPanel').style.display='flex';setTimeout(()=>$('#libraryPanel').style.display='',4000)}else $('#searchInput').focus()}
function renderProfile(){const c=$('#profileContent');if(!state.user){c.innerHTML='<p>Вы сейчас как гость.</p><button class="wide-btn" id="openLogin">Войти</button>'}else c.innerHTML=`<p><b>${esc(state.user.username)}</b></p><p>Роль: <strong>${esc(state.user.role)}</strong></p><div class="form-actions">${state.user.role==='admin'?'<button class="outline-btn" id="openAdmin">Пользователи</button>':''}<button class="outline-btn" id="changePassword">Сменить пароль</button><button class="outline-btn danger" id="logout">Выйти</button></div>`}
async function refreshMe(){state.user=(await api('/api/me')).user;$('#userName').textContent=state.user?.username||'Гость';$$('.admin-only').forEach(e=>e.style.display=state.user?.role==='admin'?'':'none');renderBooks()}
async function loadBooks(){state.books=await api('/api/books');if(!state.current&&state.books[0])openBook(state.books[0]);else if(state.current){const fresh=state.books.find(b=>b.id===state.current.id);if(fresh)openBook(fresh)}renderBooks()}
async function login(form){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.user=d.user;$('#loginError').textContent='';$('#loginModal').hidden=true;$('#profileModal').hidden=true;await refreshMe();toast('Вход выполнен')}catch(e){$('#loginError').textContent=e.message}}
async function register(form){try{await api('/api/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();toast('Читатель создан')}catch(e){toast(e.message)}}
async function changePassword(){const currentPassword=prompt('Текущий пароль:');if(currentPassword===null)return;const newPassword=prompt('Новый пароль (8–200 символов):');if(newPassword===null)return;const repeat=prompt('Повторите новый пароль:');if(newPassword!==repeat)return toast('Пароли не совпадают');try{await api('/api/auth/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});toast('Пароль изменён')}catch(e){toast(e.message)}}
function openBookForm(book=null){const f=$('#bookForm');f.reset();f.id.value=book?.id||'';f.title.value=book?.title||'';f.author.value=book?.author||'';f.description.value=book?.description||'';f.content.value=book?.content||'';$('#bookFormTitle').textContent=book?'Редактирование книги':'Новая книга';$('#bookModal').hidden=false}
async function saveBook(form){const data=Object.fromEntries(new FormData(form));try{await api(data.id?`/api/books/${data.id}`:'/api/books',{method:data.id?'PUT':'POST',body:JSON.stringify(data)});$('#bookModal').hidden=true;await loadBooks();toast('Книга сохранена')}catch(e){toast(e.message)}}
async function openAdmin(){if(state.user?.role!=='admin')return;$('#profileModal').hidden=true;$('#readerView').hidden=true;$('#adminView').hidden=false;const users=await api('/api/users');$('#userTable').innerHTML=users.map(u=>`<div class="user-row"><div><b>${esc(u.username)}</b><div class="hint">${esc(u.role)} · ${new Date(u.createdAt).toLocaleString('ru-RU')}</div></div><select class="role-select" data-role-user="${u.id}"><option value="reader" ${u.role==='reader'?'selected':''}>reader</option><option value="admin" ${u.role==='admin'?'selected':''}>admin</option></select><button class="outline-btn danger" data-delete-user="${u.id}"><i class="fa-solid fa-trash"></i></button></div>`).join('')}
function closeAdmin(){$('#adminView').hidden=true;$('#readerView').hidden=false}
function rollDie(sides){return Math.floor(Math.random()*sides)+1}
function roll(type){const a=rollDie(type==='2d6'?6:20),b=type==='2d6'?rollDie(6):0;$('#die1').textContent=a;$('#die2').textContent=type==='2d6'?b:'—';$('#diceResult').textContent=type==='2d6'?`Результат: ${a+b}`:`Результат: ${a}`}
const answers=['Бесспорно.','Да.','Пока рано решать.','Спроси после следующей страницы.','Поняша одобряет.','Лучше не знать.','Вероятность высока.','Сегодня — нет.','Знаки говорят: да.'];
function askBall(){const ball=$('#magicAnswer');$('#magicAnswer').parentElement.classList.add('shake');setTimeout(()=>{$('#magicAnswer').textContent=answers[rollDie(answers.length)-1];$('#magicAnswer').parentElement.classList.remove('shake')},400)}
function toggleGame(name){$$('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===name));$('#gameBall').classList.toggle('hidden',name!=='ball');$('#gameDice').classList.toggle('hidden',name!=='dice')}

document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close){$('#'+b.dataset.close).hidden=true;return}if(b.dataset.book){openBook(state.books.find(x=>x.id===b.dataset.book));return}if(b.dataset.themeChoice){setTheme(b.dataset.themeChoice);return}if(b.dataset.game){toggleGame(b.dataset.game);return}if(b.dataset.mobile==='search'){showSearch();return}if(b.dataset.mobile==='catalog'){state.query='';$('#searchInput').value='';renderBooks();return}if(b.dataset.mobile==='aperitif'){$('#gameBall').classList.remove('hidden');$('#gameDice').classList.add('hidden');return}if(b.dataset.mobile==='theme'){setTheme(state.theme==='anime'?'night':'anime');return}if(b.dataset.mobile==='profile'){renderProfile();$('#profileModal').hidden=false;return}if(b.id==='profileBtn'){renderProfile();$('#profileModal').hidden=false;return}if(b.id==='openLogin'){$('#profileModal').hidden=true;$('#loginModal').hidden=false;return}if(b.id==='loginForm')return;if(b.id==='logout'){await api('/api/auth/logout',{method:'POST'});state.user=null;await refreshMe();$('#profileModal').hidden=true;toast('Вы вышли');return}if(b.id==='changePassword'){changePassword();return}if(b.id==='openAdmin'||b.id==='usersBtn'){openAdmin();return}if(b.id==='adminBack'){closeAdmin();return}if(b.id==='writeBtn'||b.id==='writeBtn2'){openBookForm();return}if(b.id==='aperitifBtn'){$('#gameBall').classList.remove('hidden');$('#gameDice').classList.add('hidden');return}if(b.id==='closeAperitif'){return}if(b.id==='askBall'){askBall();return}if(b.id==='roll2d6'){roll('2d6');return}if(b.id==='rollD20'){roll('d20');return}if(b.id==='prevBtn'||b.id==='backBtn'&&false){step(-1);return}if(b.id==='nextBtn'||b.id==='nextBottom'){step(1);return}if(b.id==='bookmarkBtn'||b.id==='createBookmark'){if(state.current){const mobile=matchMedia('(max-width:800px)').matches;const p=mobile?state.page:Math.floor(state.page/2);localStorage.setItem(`bookmark:${state.current.id}`,p);renderReader();toast('Закладка сохранена')}return}if(b.id==='soundBtn'){toast('Звук включён');return}if(b.id==='fullscreenBtn'){document.documentElement.requestFullscreen?.().catch(()=>{});return}if(b.id==='settingsToggle'){b.parentElement.classList.toggle('open');return}if(b.dataset.deleteUser){if(confirm('Удалить пользователя?')){try{await api('/api/users/'+b.dataset.deleteUser,{method:'DELETE'});await openAdmin();toast('Пользователь удалён')}catch(e){toast(e.message)}}return}});
document.addEventListener('change',async e=>{if(e.target.matches('[data-role-user]')){try{await api('/api/users/'+e.target.dataset.roleUser,{method:'PUT',body:JSON.stringify({role:e.target.value})});toast('Роль обновлена')}catch(err){toast(err.message);openAdmin()}}});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login(e.currentTarget)});$('#registerForm').addEventListener('submit',e=>{e.preventDefault();register(e.currentTarget)});$('#bookForm').addEventListener('submit',e=>{e.preventDefault();saveBook(e.currentTarget)});$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderBooks()});$('#pageSlider').addEventListener('input',e=>{const mobile=matchMedia('(max-width:800px)').matches;state.page=mobile?Number(e.target.value):Number(e.target.value)*2;renderReader()});$('#prevBtn').addEventListener('click',()=>step(-1));$('#nextBtn').addEventListener('click',()=>step(1));
addEventListener('keydown',e=>{if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});addEventListener('resize',()=>state.current&&renderReader());
(async function init(){setTheme(state.theme);try{await refreshMe();await loadBooks()}catch(e){toast('API недоступен: '+e.message)}})();
